# Generated by Django 3.1.1 on 2020-10-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='mapUrl',
        ),
        migrations.AddField(
            model_name='school',
            name='map_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='school',
            name='short_description',
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='school',
            name='accrate',
            field=models.CharField(blank=True, choices=[('3.0-3.9%', '3.0-3.9%'), ('4.0-4.9%', '4.0-4.9%'), ('5.0-5.9%', '5.0-5.9%'), ('6.0-6.9%', '6.0-6.9%'), ('7.0-7.9%', '7.0-7.9%'), ('8.0-8.9%', '8.0-8.9%'), ('9.0-9.9%', '9.0-9.9%')], default='Select accrate', max_length=64),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, choices=[('New York, NY', 'New York, NY'),('Cambridge, MA', 'Cambridge, MA'),('Princeton, NJ', 'Princeton, NJ'),('New Haven, CT', 'New Haven, CT'),('Providence, RI', 'Providence, RI'),('Philadelphia, PA', 'Philadelphia, PA'),('Hanover, NH', 'Hanover, NH'),('Ithaca, NY', 'Ithaca, NY')], default='Select location', max_length=64),
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=64)),
                ('book_number', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
