# Generated by Django 3.1.1 on 2020-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclub', '0003_remove_UNiversities_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='UNiversities',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
